### ISSUE TITLE
Add unit tests for command-line

### ISSUE THREAD

**Issue by agstephens** [roocs/daops#97]
- [ ] Create `tests/test_cli.py`
- [ ] Copy this test into that module (and rename it): 
  - https://github.com/roocs/daops/blob/master/tests/test_operations/test_subset.py#L463-L488
- [ ] Start by checking you can run it with: `python -m pytest -c null tests/test_cli.py`
- [ ] Then change it so that it calls `daops` from the command-line instead of from inside python
- [ ] Once it is all working, go into `tests/test_operations/test_subset.py` and copy these tests into `tests/test_cli.py` (renaming them as being called by `cli`:
  - [ ] https://github.com/roocs/daops/blob/master/tests/test_operations/test_subset.py#L131
  - [ ] https://github.com/roocs/daops/blob/master/tests/test_operations/test_subset.py#L160
  - [ ] https://github.com/roocs/daops/blob/master/tests/test_operations/test_subset.py#L306
  - [ ] https://github.com/roocs/daops/blob/master/tests/test_operations/test_subset.py#L360
  - [ ] https://github.com/roocs/daops/blob/master/tests/test_operations/test_subset.py#L428
  - [ ] https://github.com/roocs/daops/blob/master/tests/test_operations/test_subset.py#L518

**Comment by agstephens** [comment]
@alaniwi : here is how to use `level_interval`: 

https://github.com/roocs/clisops/blob/21ef1efa82808f653c6c1d958beb50e3a2ae1e7c/tests/ops/test_subset.py#L213

Use of `LevelParameter`:

https://github.com/roocs/roocs-utils/search?q=levelparameter

**Comment by alaniwi** [comment]
@agstephens I am not using `level_interval` or `level_parameter` because I have tested that everything can be passed through as strings provided that the format is correct. I think when I tested it previously and it didn't work, I didn't know what that format looked like. So I was able to strip code out of cli.py.

In `test_cli.py`, I am making sure to pass everything through as strings. All the tests are passing and I am closing this issue now.

I have not retained your example code for `test_cli.py` at all - now completely replaced with one based on `test_subset.py` - but it was helpful to see it. For convenience, here is the commit ID in the history where you added it: 72ad50567d4be2b1ed55eb1b9eab1dac789fccde
